### ISSUE TITLE
Refactor ProposeAtomicSwapFlow not to pass securityLinearId as the argument

### ISSUE THREAD

**Issue by etaroid** [LayerXcom/cordage#17]
The Counterparty node will search this security state with vaultQuery in SettleAtomicSwapFlow.

**Comment by shun-tak** [comment]
this might be fixed by using Token SDK
https://github.com/LayerXcom/cordage/issues/13

**Comment by shun-tak** [comment]
linearId must be specified even if it is using token SDK
